package Modelo;

public enum Eventos {
	SELECCIONAR_FICHA,
	SELECCIONAR_CASILLA,
	ERROR_FICHA_SELECCIONADA,
	ERROR_CASILLA_SELECCIONADA,
	ERROR_MOVIMIENTO_INVALIDO,
	ERROR_MOVIMIENTO_COMER_DISPONIBLE,
	FICHA_SELECCIONADA,
	MOVIMIENTO_REALIZADO, 
	SELECCIONAR_JUGADORES, 
	INFORMAR_GANADOR, 
	ACTUALIZAR_TABLERO, 
	CAMBIAR_TURNO, 
	JUEGO_INICIADO, 
	COLOR_YA_ASIGNADO, 
	JUGADOR_YA_ASIGNADO, 
	JUGADORES_INSUFICIENTES, 
	JUGADOR_SELECCIONADO,
	DESELECCIONAR_FICHA, 
	JUGADOR_EXISTENTE, 
	JUGADOR_AGREGADO, 
	JUGADOR_ELIMINADO; 
	
}
